lib/yo_web/router.ex
defmodule YoWeb.Router do
  @moduledoc false

  use YoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug YoWeb.Plugs.Count
  end

  pipeline :admin do
    plug :put_layout, {YoWeb.LayoutView, "admin.html"}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", YoWeb do
    pipe_through :browser

    resources "/posts", PostController, only: [:show]
    post "/posts/:post_id/add_comment", PostController, :add_comment

    get "/", PostController, :index
  end

  scope "/admin", YoWeb.Admin, as: :admin do
    pipe_through [:browser, :admin]
    resources "/posts", PostController
  end

  scope "/api", YoWeb.Api do
    pipe_through :api
    resources "/posts", PostController, only: [:show, :index]
  end
end

lib/yo_web/views/layout_view.ex
defmodule YoWeb.LayoutView do
  @moduledoc false

  use YoWeb, :view
end

lib/yo_web/templates/layout/_alerts.html.eex
<%= if get_flash(@conn, :info) do %>
  <article class="alert alert-info closable-js" role="alert">
    <%= get_flash(@conn, :info) %>
    <span class="close close-js">&times;</span>
  </article>
<% end %>

<%= if get_flash(@conn, :error) do %>
  <article class="alert alert-error closable-js" role="alert">
    <%= get_flash(@conn, :error) %>
    <span class="close close-js">&times;</span>
  </article>
<% end %>

lib/yo_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Elixir Workshop</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body class="body admin">
    <header class="site-header">
      <%= link "Home", to: Routes.post_path(@conn, :index), class: "header-link" %>
      <strong>Admin</strong>
      <%= link "Admin", to: Routes.admin_post_path(@conn, :index), class: "header-link" %>
    </header>
    <main role="main" class="site-main">
      <%= render("_alerts.html", conn: @conn) %>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/yo_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Elixir Workshop</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body class="body">
    <header class="site-header">
      <%= link "Home", to: Routes.post_path(@conn, :index), class: "header-link" %>
      Views: <%= @conn.assigns.counter %>
      <%= link "Admin", to: Routes.admin_post_path(@conn, :index), class: "header-link" %>
    </header>
    <main role="main" class="site-main">
      <%= render("_alerts.html", conn: @conn) %>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>